services:

  database:
    image: postgres:17-alpine
    container_name: database
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  adminer:
    image: adminer:5
    container_name: postgres_gui
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - database

  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: